
WITH TB_START AS (
    SELECT  substr(DtCriacao, 0, 8) AS DtMes,
            count(distinct IdCliente) AS MAU

    FROM TRANSACOES

    GROUP BY DtMes

    ORDER BY DtMes DESC
),

-- O INDICADOR N É JUSTO, POIS ALGUNS MESES PODEM TER MAIS DIAS DO QUE OUTROS!
-- A IDEIA É USAR 28 DIAS, POIS COM 28 DIAS TODOS OS MESES TERÃO A MESMA QUANTIDADE E O MES FICA COM 4 SEMANAS...


TB_DAILY AS (
    SELECT DISTINCT
            DATE(substr(DtCriacao, 0, 11)) AS DtDia,
            IdCliente

    FROM TRANSACOES

    ORDER BY DtDia ASC
),

TB_DISTINCT_DAY AS (

SELECT  DISTINCT
        DtdIA AS dtRef

FROM TB_DAILY)

-- CADA DIA É UMA DATA QUE OLHA PARA 28 DIAS NO PASSADO! TODO DIA ESTÁ CALCULANDO O MAU DOS ÚLTIMOS 28 DIAS!

SELECT T1.DtRef,
       count(DISTINCT T2.IdCliente) AS MAU_28_DIAS,
       COUNT(DISTINCT T2.DTDIA) AS DIAS_COM_TRANSACAO

FROM TB_DISTINCT_DAY AS T1
LEFT JOIN TB_DAILY AS T2
ON T2.DtDia <= T1.dtRef
AND julianday(T1.dtRef) - julianday(T2.DtDia) < 28 -- TRANSFORMA O DIA EM NÚMEROS PARA SUBTRAIR, QUEREMOS < 28 POIS TEM O DIA 0 Já

GROUP BY T1.dtRef

ORDER BY t1.dtref ASC